import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { $ } from 'bun'

const INSTANCE_NAME = 'browseros-vm-smoke'
const SOCKET_POLL_INTERVAL_MS = 2000
const SOCKET_POLL_TIMEOUT_MS = 120_000

export interface BootProbeOptions {
  limactlPath?: string
}

export async function bootAndProbe(
  qcowZstPath: string,
  opts: BootProbeOptions = {},
): Promise<void> {
  const limactl = opts.limactlPath ?? 'limactl'
  const workDir = await mkdtemp(path.join(tmpdir(), 'vm-smoke-'))
  const qcowPath = path.join(workDir, 'disk.qcow2')
  const configPath = path.join(workDir, 'lima.yaml')
  const sockPath = path.join(workDir, 'podman.sock')

  try {
    await $`zstd -d -f -o ${qcowPath} ${qcowZstPath}`.quiet()
    await writeFile(configPath, composeLimaConfig(qcowPath, sockPath))
    await $`${limactl} start --name=${INSTANCE_NAME} --tty=false ${configPath}`
    await waitForSocket(sockPath)
    await probePodmanSocket(sockPath)
  } finally {
    await $`${limactl} stop --force ${INSTANCE_NAME}`.quiet().nothrow()
    await $`${limactl} delete --force ${INSTANCE_NAME}`.quiet().nothrow()
    await rm(workDir, { recursive: true, force: true })
  }
}

export function composeLimaConfig(qcowPath: string, sockPath: string): string {
  return `# Generated by @browseros/vm-container smoke test
vmType: qemu
images:
  - location: ${qcowPath}
    arch: x86_64
containerd:
  system: false
  user: false
mounts: []
provision: []
portForwards:
  - guestSocket: /run/podman/podman.sock
    hostSocket: ${sockPath}
    proto: unix
`
}

async function waitForSocket(sockPath: string): Promise<void> {
  const deadline = Date.now() + SOCKET_POLL_TIMEOUT_MS
  while (Date.now() < deadline) {
    const file = Bun.file(sockPath)
    if (await file.exists()) return
    await Bun.sleep(SOCKET_POLL_INTERVAL_MS)
  }
  throw new Error(
    `podman socket did not appear within ${SOCKET_POLL_TIMEOUT_MS}ms: ${sockPath}`,
  )
}

async function probePodmanSocket(sockPath: string): Promise<void> {
  const response = await fetch('http://d/v4.0.0/libpod/_ping', {
    unix: sockPath,
  } as RequestInit)
  if (!response.ok) {
    throw new Error(`podman ping failed: ${response.status}`)
  }
  const body = (await response.text()).trim()
  if (body !== 'OK') {
    throw new Error(`podman ping body unexpected: ${body}`)
  }
}
